language: c
matrix:
  include:
    - name: "Windows gcc C"
      os: windows
      compiler: gcc
      env: MAKE="make" CMAKE_GENERATOR="MinGW Makefiles"
    - name: "Windows clang C"
      os: windows
      compiler: clang
      env: MAKE="make" CMAKE_GENERATOR="MinGW Makefiles"
    - name: "Linux gcc C"
      os: linux
      compiler: gcc
      env: MAKE="make" CMAKE_GENERATOR="Unix Makefiles"
    - name: "Linux clang C"
      os: linux
      compiler: clang
      env: MAKE="make" CMAKE_GENERATOR="Unix Makefiles"

before_script:
  - if ["$TRAVIS_OS_NAME" = "windows" ]; then choco install make; fi
  - cmake --version
  - mkdir build
  - cd build
  - if ["$TRAVIS_OS_NAME" = "windows" ]; then cmd -c cmake -B . -S $TRAVIS_BUILD_DIR; else cmake -B . -S $TRAVIS_BUILD_DIR; fi

script:
  - $MAKE all
