os: windows
language: c
matrix:
  include:
    - name: "Windows gcc C"
      env: CC="gcc.exe" CXX="g++.exe" AR="ar.exe" LD="g++.exe" WINDRES="windres.exe"
    - name: "Windows clang C"
      env: CC="clang.exe" CXX="clang++.exe" AR="llvm-ar.exe" LD="clang++.exe" WINDRES="windres.exe"
script:
  - "mingw32-make.exe" CC=$CC CXX=$CXX AR=$AR LD=$LD WINDRES=$WINDRES -f "Makefile.win" lib_fullyoptimized lib_release