language: c
jobs:
  include:
    - name: "Bionic gcc C"
      os: linux
      dist: bionic
      compiler: gcc
      env: MAKE="make" CMAKE_GENERATOR="Unix Makefiles" TEST_EXE_NAME="src/creq_test"
    - name: "Bionic clang C"
      os: linux
      dist: bionic
      compiler: clang
      env: MAKE="make" CMAKE_GENERATOR="Unix Makefiles" TEST_EXE_NAME="src/creq_test"

before_install:
  - sudo apt-get update
  - sudo apt-get -y install doxygen graphviz

before_script:
  - cmake --version
  - doxygen -v
  - mkdir build
  - cd build
  - cmake -B . -S $TRAVIS_BUILD_DIR -DBUILD_DOCUMENTATION=true

script:
  - $MAKE all
  - $TRAVIS_BUILD_DIR/build/$TEST_EXE_NAME
  - $MAKE doc

before_deploy:
  - cd $TRAVIS_BUILD_DIR/
  - mkdir release
  - cp src/creq.c release/creq.c
  - cp src/creq.h release/creq.h
  - cp lib/c-vector/c-vector.h release/c-vector.h
  - cp lib/c-vector/c-vector.c release/c-vector.c
  - zip -q -r release.zip release/*

deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file: "release.zip"
  skip_cleanup: true
  on:
    tags: true