language: c
matrix:
  include:
    - name: "Linux gcc C"
      os: linux
      compiler: gcc
      env: MAKE="make" CMAKE_GENERATOR="Unix Makefiles"
    - name: "Linux clang C"
      os: linux
      compiler: clang
      env: MAKE="make" CMAKE_GENERATOR="Unix Makefiles"

before_script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake -B . -S $TRAVIS_BUILD_DIR

script:
  - $MAKE all
