
language: c
matrix:
  include:
    - name: "Windows gcc C"
      os: windows
      env: MAKEFILE="Makefile.win" MAKE="mingw32-make.exe" CC="gcc.exe" CXX="g++.exe" AR="ar.exe" LD="g++.exe" WINDRES="windres.exe" ADD_CFLAGS="" ADD_LDFLAGS=""
#   - name: "Windows clang C"
#     os: windows
#     env: CC="clang.exe" CXX="clang++.exe" AR="llvm-ar.exe" LD="clang++.exe" WINDRES="windres.exe" ADD_CFLAGS="--target=i686-pc-mingw32" ADD_LDFLAGS="--target=i686-pc-mingw32"
    - name: "Linux gcc C"
      os: linux
      env: MAKEFILE="Makefile" MAKE="make" CC="gcc" CXX="g++" AR="ar" LD="g++" WINDRES="windres" ADD_CFLAGS="" ADD_LDFLAGS=""
script:
  - $MAKE CC=$CC CXX=$CXX AR=$AR LD=$LD WINDRES=$WINDRES ADD_CFLAGS=$ADD_CFLAGS ADD_LDFLAGS=$ADD_LDFLAGS -f $MAKEFILE lib_release