language: c
matrix:
  include:
    - name: "Windows gcc C"
      os: windows
      compiler: gcc
      env: MAKE="mingw32-make.exe" CMAKE_GENERATOR="MinGW Makefiles"
    - name: "Windows clang C"
      os: windows
      compiler: clang
      env: MAKE="mingw32-make.exe" CMAKE_GENERATOR="MinGW Makefiles"
    - name: "Linux gcc C"
      os: linux
      compiler: gcc
      env: MAKE="make" CMAKE_GENERATOR="Unix Makefiles"
    - name: "Linux clang C"
      os: linux
      compiler: clang
      env: MAKE="make" CMAKE_GENERATOR="Unix Makefiles"

before_script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake -B . -S $TRAVIS_BUILD_DIR

script:
  - $MAKE all
