language: c
jobs:
  include:
    - name: "Bionic gcc C"
      os: linux
      dist: bionic
      compiler: gcc
      env: MAKE="make" CMAKE_GENERATOR="Unix Makefiles" TEST_EXE_NAME="src/creq_test"
    - name: "Bionic clang C"
      os: linux
      dist: bionic
      compiler: clang
      env: MAKE="make" CMAKE_GENERATOR="Unix Makefiles" TEST_EXE_NAME="src/creq_test"

before_script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake -B . -S $TRAVIS_BUILD_DIR

script:
  - $MAKE all
  - $TRAVIS_BUILD_DIR/build/$TEST_EXE_NAME
